import type { ShoeMatch } from './database';

/**
 * Shoe reference database — generated from `data/shoes-database.csv`
 * (cloud-3: converted from a runtime `fs.readFileSync` seed load to a
 * build-time literal so this module has zero filesystem dependency and is
 * safe to import on both the node and workerd runtime paths).
 *
 * If you need to add/edit entries, edit `data/shoes-database.csv` (kept as
 * the human-editable source of truth) and regenerate this file — there is
 * no automated build step for that yet; the CSV -> array conversion is a
 * straightforward one-off script (see cloud-3 commit for the generator
 * used to produce this file).
 */
export const SHOES_DATABASE: ShoeMatch[] = [
  { brand: 'Saucony', model: 'Endorphin Pro 3', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Saucony', model: 'Endorphin Pro 4', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Saucony', model: 'Endorphin Pro Elite', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: 'top-tier race' },
  { brand: 'Saucony', model: 'Endorphin Elite', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Saucony', model: 'Endorphin Elite 2', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Saucony', model: 'Endorphin Speed 3', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: 'nylon plate' },
  { brand: 'Saucony', model: 'Endorphin Speed 4', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: 'nylon plate' },
  { brand: 'Saucony', model: 'Endorphin Shift 3', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Endorphin Shift 4', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Kinvara 14', recommendedKm: 500, category: 'daily', carbonPlate: false, notes: 'minimal' },
  { brand: 'Saucony', model: 'Kinvara 15', recommendedKm: 500, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Ride 16', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Ride 17', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Ride 18', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Triumph 21', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Saucony', model: 'Triumph 22', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Guide 17', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Saucony', model: 'Hurricane 24', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability max cushion' },
  { brand: 'Saucony', model: 'Peregrine 14', recommendedKm: 700, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Saucony', model: 'Xodus Ultra 3', recommendedKm: 800, category: 'trail', carbonPlate: false, notes: 'ultra' },
  { brand: 'Saucony', model: 'Type A9', recommendedKm: 300, category: 'race-day', carbonPlate: false, notes: 'track flat' },
  { brand: 'Hoka', model: 'Cielo X1', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Hoka', model: 'Rocket X 2', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Hoka', model: 'Mach 6', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Mach X', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: 'plated' },
  { brand: 'Hoka', model: 'Mach X 2', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Clifton 9', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Clifton 10', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Bondi 8', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Hoka', model: 'Bondi 9', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Arahi 7', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Hoka', model: 'Arahi 8', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Skyward X', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Hoka', model: 'Rincon 4', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: 'minimal cushion' },
  { brand: 'Hoka', model: 'Speedgoat 5', recommendedKm: 700, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Speedgoat 6', recommendedKm: 700, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Stinson 7', recommendedKm: 800, category: 'trail', carbonPlate: false, notes: 'max cushion trail' },
  { brand: 'Hoka', model: 'Tecton X 2', recommendedKm: 500, category: 'trail', carbonPlate: true, notes: 'carbon trail' },
  { brand: 'Hoka', model: 'Challenger 7', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Hoka', model: 'Torrent 3', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Vaporfly 3', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Vaporfly 4', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Alphafly 3', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Streakfly', recommendedKm: 350, category: 'race-day', carbonPlate: false, notes: 'short race flat' },
  { brand: 'Nike', model: 'Pegasus 41', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Pegasus 42', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Pegasus Plus', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Pegasus Premium', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Pegasus Trail 5', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Vomero 17', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Vomero 18', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Nike', model: 'Structure 25', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Nike', model: 'Invincible 3', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Nike', model: 'Zoom Fly 5', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Zoom Fly 6', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Ultrafly', recommendedKm: 500, category: 'trail', carbonPlate: true, notes: undefined },
  { brand: 'Nike', model: 'Wildhorse 8', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Sky+', recommendedKm: 500, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Sky Paris', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Sky Tokyo', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Edge+', recommendedKm: 500, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Edge Paris', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Metaspeed Edge Tokyo', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Magic Speed 4', recommendedKm: 500, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Magic Speed 3', recommendedKm: 500, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Superblast 2', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Superblast', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Novablast 4', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Novablast 5', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Gel-Cumulus 26', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Gel-Cumulus 27', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Gel-Nimbus 26', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'ASICS', model: 'Gel-Nimbus 27', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Gel-Kayano 31', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'ASICS', model: 'Gel-Kayano 32', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'GT-2000 13', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'ASICS', model: 'Gel-Trabuco 12', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Fujispeed 3', recommendedKm: 500, category: 'trail', carbonPlate: true, notes: undefined },
  { brand: 'ASICS', model: 'Fujitrabuco 3', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'ASICS', model: 'Hyper Speed 3', recommendedKm: 400, category: 'race-day', carbonPlate: false, notes: 'track flat' },
  { brand: 'Brooks', model: 'Hyperion Elite 4', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Brooks', model: 'Hyperion Max 2', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Brooks', model: 'Hyperion 2', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Ghost 16', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Ghost 17', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Glycerin 21', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Brooks', model: 'Glycerin 22', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Glycerin GTS 21', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Brooks', model: 'Adrenaline GTS 24', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Brooks', model: 'Launch 10', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Caldera 7', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Cascadia 18', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Brooks', model: 'Catamount 4', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloudboom Echo 3', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'On', model: 'Cloudboom Strike', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'On', model: 'Cloudmonster Hyper', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'On', model: 'Cloudmonster 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloudsurfer', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloudsurfer 7', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloudflow', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloud 5', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: 'casual' },
  { brand: 'On', model: 'Cloudultra 2', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: 'ultra' },
  { brand: 'On', model: 'Cloudvista', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'On', model: 'Cloudventure', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: 'FuelCell SuperComp Elite v4', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'New Balance', model: 'FuelCell SuperComp Trainer v3', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'New Balance', model: 'FuelCell Rebel v4', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: 'FuelCell Rebel v5', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: '1080 v13', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: '1080 v14', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: '860 v14', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'New Balance', model: 'Vongo v6', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'New Balance', model: 'More v5', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'New Balance', model: 'Hierro v8', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'New Balance', model: 'Summit Unknown v5', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Adidas', model: 'Adios Pro 3', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Adidas', model: 'Adios Pro 4', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Adidas', model: 'Adios Pro Evo 1', recommendedKm: 200, category: 'race-day', carbonPlate: true, notes: 'one-race shoe' },
  { brand: 'Adidas', model: 'Adizero Boston 12', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Adidas', model: 'Adizero Boston 13', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Adidas', model: 'Adizero SL 2', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Adidas', model: 'Adizero Adios 8', recommendedKm: 500, category: 'race-day', carbonPlate: false, notes: undefined },
  { brand: 'Adidas', model: 'Supernova Rise', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Adidas', model: 'Supernova Solution', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Adidas', model: 'Ultraboost Light', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Adidas', model: 'Terrex Agravic Speed', recommendedKm: 500, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Adidas', model: 'Terrex Agravic Pro', recommendedKm: 500, category: 'trail', carbonPlate: true, notes: 'carbon trail' },
  { brand: 'Altra', model: 'Vanish Tempo', recommendedKm: 500, category: 'uptempo', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Mont Blanc BOA', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Lone Peak 8', recommendedKm: 800, category: 'trail', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Lone Peak 9', recommendedKm: 800, category: 'trail', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Olympus 6', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: 'zero-drop max cushion' },
  { brand: 'Altra', model: 'Outroad 2', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Altra', model: 'Escalante 4', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Torin 7', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'zero-drop' },
  { brand: 'Altra', model: 'Provision 8', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Mizuno', model: 'Wave Rebellion Pro 3', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Mizuno', model: 'Wave Rebellion Flash 2', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Mizuno', model: 'Wave Sky 7', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Mizuno', model: 'Wave Rider 28', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Mizuno', model: 'Wave Inspire 20', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Mizuno', model: 'Wave Mujin 9', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Mizuno', model: 'Wave Daichi 7', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'S/Lab Ultra 4', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: 'ultra' },
  { brand: 'Salomon', model: 'Pulsar Trail Pro 2', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'Genesis', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'Speedcross 6', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'Sense Ride 5', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'Glide Max TR', recommendedKm: 800, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Salomon', model: 'Aero Glide 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Topo', model: 'Cyclone 2', recommendedKm: 500, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Topo', model: 'Specter 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Topo', model: 'Phantom 3', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Topo', model: 'Ultraventure 4', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Topo', model: 'MTN Racer 3', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Puma', model: 'Deviate Nitro Elite 3', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Puma', model: 'Deviate Nitro 3', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Puma', model: 'Velocity Nitro 3', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Puma', model: 'Magnify Nitro 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'max cushion' },
  { brand: 'Puma', model: 'ForeverRun Nitro 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: 'stability' },
  { brand: 'Diadora', model: 'Nucleo', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Diadora', model: 'Mythos Blushield Volo', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Diadora', model: 'Atomo', recommendedKm: 650, category: 'super-trainer', carbonPlate: false, notes: undefined },
  { brand: 'Reebok', model: 'FloatRide Run Energy 5', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Under Armour', model: 'Velociti 3', recommendedKm: 650, category: 'uptempo', carbonPlate: false, notes: undefined },
  { brand: 'Under Armour', model: 'Infinite Pro', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Under Armour', model: 'HOVR Sonic 6', recommendedKm: 650, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Skechers', model: 'GO Run Razor Excess 2', recommendedKm: 500, category: 'race-day', carbonPlate: false, notes: undefined },
  { brand: 'Skechers', model: 'GO Run Persistence', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Skechers', model: 'Speed Beast', recommendedKm: 650, category: 'super-trainer', carbonPlate: true, notes: undefined },
  { brand: 'Inov-8', model: 'Trailfly Ultra G 300 Max', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: 'ultra' },
  { brand: 'Inov-8', model: 'X-Talon G 235 v2', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: 'fell' },
  { brand: 'Inov-8', model: 'Mudclaw G 260 v2', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: 'fell' },
  { brand: 'La Sportiva', model: 'Bushido III', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'La Sportiva', model: 'Cyklon Cross GTX', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'La Sportiva', model: 'Prodigio Pro', recommendedKm: 650, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'La Sportiva', model: 'Mutant', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'La Sportiva', model: 'Akasha II', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Scarpa', model: 'Ribelle Run XT', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Scarpa', model: 'Spin Planet', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Merrell', model: 'Agility Peak 5', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Merrell', model: 'Long Sky 2', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Merrell', model: 'MTL Long Sky', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Tracksmith', model: 'Eliot Runner', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Tracksmith', model: 'Eliot Racer', recommendedKm: 400, category: 'race-day', carbonPlate: false, notes: undefined },
  { brand: 'Norda', model: '001', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Norda', model: '002', recommendedKm: 500, category: 'race-day', carbonPlate: true, notes: 'trail carbon' },
  { brand: 'Speedland', model: 'SL:PDX', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Speedland', model: 'SL:HSV', recommendedKm: 500, category: 'trail', carbonPlate: true, notes: undefined },
  { brand: 'Craft', model: 'Pro Endur Distance', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Craft', model: 'Endurance Trail', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Lululemon', model: 'Beyondfeel', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Lululemon', model: 'Blissfeel 2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Tarkine', model: 'Goshawk V2', recommendedKm: 800, category: 'daily', carbonPlate: false, notes: undefined },
  { brand: 'Tarkine', model: 'Trail Devil', recommendedKm: 750, category: 'trail', carbonPlate: false, notes: undefined },
  { brand: 'Anta', model: 'C202 GT', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Xtep', model: '160X 5.0', recommendedKm: 400, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: '361', model: 'Eros 2 Pro', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
  { brand: 'Li-Ning', model: 'Feidian 4 Ultra', recommendedKm: 450, category: 'race-day', carbonPlate: true, notes: undefined },
];
